### ISSUE TITLE
4 Extra Points

### ISSUE THREAD

**Issue by danipalli** [htl-perg-2019-20-5ahif/highscore-exercise-danipalli#1]
Dear Mr. Stropek,

I implemented all of the requirements (1 Point MC + 1 Point POSE-C#).
Additionally I store the highscore list in a mssql database and not in memory (1 Point POSE-C#) and wrote a `docker-compose` file with which a user can start the whole backend + client (1 Point MC).

I pushed all images to my Docker Hub account, so you can simlply run the `docker-compose` file.

Kind regards
Daniel Pallinger

**Comment by rstropek** [comment]
Hi @danipalli!

Thank you for the homework. Well done 👍, I could really use the *docker-compose* file and it immediately worked 🤩.

Greetings,
Rainer Stropek.
